# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aWqhkVA1HUMnJ87bpk2QQB97yvcdjNul

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

s="Hi there Sam!"
y=s.split()
y

"""## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

planet = "Earth"
diameter = "12742"
a="The diameter of "
b=" is "
c=" kilometers."
a+planet+b+diameter+c

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

import numpy as np
a=np.zeros(10)
a

import numpy as np
a=np.ones(10)
a*5

"""## 5. Create an array of all the even integers from 20 to 35"""

import numpy as np
a=np.arange(20,35,2)
a

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

import numpy as np
a=np.arange(0,9).reshape(3,3)
a

"""## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

import numpy as np
a = np.array([1, 2, 3]),
b = np.array([4, 5, 6]),
np.concatenate((a,b))

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

import pandas as pd
d={'name':['abc','xyz']}
df=pd.DataFrame(d)
df

import pandas as pd
d={'name':['abc','xyz'],'age':[20,21]}
df=pd.DataFrame(d)
df

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

import datetime
day_delta = datetime.timedelta(days=1) 
start_date = datetime.date.today()
end_date = start_date + 7*day_delta

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

import pandas as pd    
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]   
df = pd.DataFrame(lists, columns =['rollno', 'name','age']) 
df